rvm:
  - 2.0.0

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role neighborly SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database neighborly_test;' -U neighborly postgres"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake db:migrate"

env:
  - DISPLAY=:99.0

script:
  - "bundle exec rspec spec"

branches:
  only:
    - master
    - production
    - new-ui
